Api gateway - Ready for QA
WithSecureLabs/cloud-wiki pull request #47
Opened 2022-10-12 13:39 UTC by matthewkeogh50

initial API GW page

2022-10-26 17:22 UTC, NJonesUK requested changes

2022-10-26 17:22 UTC, NJonesUK commented on docs/aws/services/API_Gateway.md
> +### Catching
Spelling

2022-10-26 17:22 UTC, NJonesUK commented on docs/aws/services/API_Gateway.md
> +Authorizers provide the ability to authenticate users/systems with an API endpoint via a Lambda function or Cognito user pool. API GW will create a resource policy based on the chosen function or use
Can we expand a bit on how authorizers work?

2022-10-26 17:22 UTC, NJonesUK commented on docs/aws/services/API_Gateway.md
> +- TLS and SSL support available.
What do we mean here? SSL's the old version of the TLS protocol, right? Are they still supporting SSLv3 for some reason?

2022-12-03 22:46 UTC, matthewkeogh50 commented on docs/aws/services/API_Gateway.md
> +- TLS and SSL support available.
my mistake - you're right. SSLv3 is not supported according to https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-custom-domain-tls-version.html 

Needs to be at least TLSv1 - I'll update

2022-12-16 11:04 UTC, NJonesUK approved these changes

2022-12-16 11:04 UTC, merged